Us 02 -As a user, I should access to the Oroinc Documentation page. (Window handle)
Ahmtfrks/FleetManagementProjectCucumber_Group2 pull request #12
Opened 2024-01-13 07:33 UTC by ZikkJ

2024-01-13 19:18 UTC, mujganaydin requested changes

2024-01-13 19:18 UTC, mujganaydin commented on src/test/java/com/fleetmanagement/stepDefinitions/US_02_OroincDocumentationPageStepDefinition.java
> +        Driver.closeDriver();
You don't need to call `closeDriver() ` because it's already called in `com.fleetmanagement.stepDefinitions.Hooks#teardownMethod()`.

2024-01-13 19:18 UTC, mujganaydin commented on src/test/resources/features/US_02_OroincDocumentationpage.feature
> +    Given the user is on the Dashboard page
You don't need to give this `Background` step because it's already called in `com.fleetmanagement.stepDefinitions.Hooks#setupMethod()` thanks to Hooks mechanism.

2024-01-15 20:04 UTC, ZikkJ commented on src/test/java/com/fleetmanagement/stepDefinitions/US_02_OroincDocumentationPageStepDefinition.java
> +        Driver.closeDriver();
Thanks Mujgan, I deleted closeDriver() step.

2024-01-15 20:05 UTC, ZikkJ commented on src/test/resources/features/US_02_OroincDocumentationpage.feature
> +    Given the user is on the Dashboard page
Also I deleted Background, thanks.

2024-01-15 22:08 UTC, merged